global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'booking'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080'] 
  - job_name: 'hotel'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8090'] 
  - job_name: 'mailserver'
    metrics_path: '/actuator/prometheus'
    static_configs: 
      - targets: ['localhost:9000']
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082'] 
